### ISSUE TITLE
Meaning of parameter `--frame_range 0-10`

### ISSUE THREAD

**Issue by peterwilson3912** [facebookresearch/robust_cvd#12]
Thanks for the amazing project! I'm wondering the meaning of this parameter:
`--frame_range 0-10`

In params.py file it says:
```
        self.parser.add_argument(
            "--frame_range", default="",
            type=frame_range.parse_frame_range,
            help="Range of depth to fine-tune, e.g., 0,2-10,21-40."
        )

```

I set it to 10 and in the end I got 10 raw file in 

`./R0-10_hierarchical2_midas2/StD100.0_StR1.0_SmD0_SmR0.0/depth_e0000/e0000_filtered/depth/`

Does this mean it only processes the first 10 frames in the video? Is there any easy way to make it process the whole video (all frames) automatically? Thanks a lot!

**Comment by jbhuang0604** [comment]
Yes, you can simply not include the `--frame_range` parameter. It's useful parameter when you need to process specific video range.
