### ISSUE TITLE
About downloading models

### ISSUE THREAD

**Issue by Minisal** [facebookresearch/robust_cvd#14]
wget https://www.dropbox.com/s/v1oc39d8k5fa1zx/models.zip?dl=1 -O models.zip

I tried many methods many times, such as wget and browser, but all failed to download the model.
Is there any other download link? For example, Baidu Netdisk?

**Comment by ionvision** [comment]
You can also try this Weiyun link:

https://share.weiyun.com/ESR1g1hU

**Comment by Minisal** [comment]
I have successfully downloaded the model, thank you!
