### ISSUE TITLE
Unable to download pretrained models

### ISSUE THREAD

**Issue by AlverGant** [facebookresearch/robust_cvd#31]
Hi!

The dropbox download link gives a 404 and the alternative download link needs a WeChat account for downloading the models.

I kindly ask you to please share the models in a more straightforward way.

Thank you and best regards!

**Comment by ionvision** [comment]
Hey, just updated the dropbox link in Colab:

https://www.dropbox.com/s/avruiwv95c5xucn/models.zip?dl=0

Let me know if any other issue arises.
