### ISSUE TITLE
ERROR: 500 frames extracted, but 0 PTS entries. can anyone please help me with this error?

### ISSUE THREAD

**Issue by MNadeemDev** [facebookresearch/robust_cvd#36]

**Comment by MNadeemDev** [comment]
solved

**Comment by manhkhanhad** [comment]
I come across this issue. How to fix it? @muhammadnadeem23064

**Comment by relh** [comment]
I think it's an FFMPEG issue.. make sure your `/usr/local/bin/ffmpeg/` links to a `/usr/bin/ffmpeg` instead of one in your anaconda (and same for ffprobe)
