### ISSUE TITLE
Problems in your previous version

### ISSUE THREAD

**Issue by peterwilson3912** [facebookresearch/robust_cvd#8]
Hey there! I run your previous version of code and got half of the results and met this problem:

https://github.com/facebookresearch/consistent_depth/issues/4#issuecomment-680177616

May I ask could you please help me with this?

**Comment by ionvision** [comment]
I would suggest contacting the first author of the previous paper, Xuan Luo, to resolve this COLMAP related issue. She's quite reachable.
